# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  backend_sockets:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_sockets
    hostname: backend_sockets
    ports:
      - '8080:8080'
    # links:
    #   - database
    # depends_on:
    #   - database
    volumes:
      - ./backend:/usr/src/backend
    networks:
      - default
  
  front_react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front_react
    networks:
      - default
    depends_on:
      - backend_sockets
    ports:
      - '3000:3000'
    volumes:
      - './frontend/app:/usr/src/app'
      - '/usr/src/app/node_modules'
